FLAGS = {
    "flag_ac": ["en"],
    "flag_ad": ["ca"],
    "flag_ae": ["ar"],
    "flag_af": ["ps", "fa"],
    "flag_ag": ["en"],
    "flag_ai": ["en"],
    "flag_al": ["sq"],
    "flag_am": ["hy"],
    "flag_ao": ["pt"],
    "flag_aq": ["en"],
    "flag_ar": ["es"],
    "flag_as": ["sm", "en"],
    "flag_at": ["de"],
    "flag_au": ["en"],
    "flag_aw": ["nl"],
    "flag_ax": ["sv"],
    "flag_az": ["az"],
    "flag_ba": ["bs", "sr", "hr"],
    "flag_bb": ["en"],
    "flag_bd": ["bn"],
    "flag_be": ["fr", "nl", "de"],
    "flag_bf": ["fr"],
    "flag_bg": ["bg"],
    "flag_bh": ["ar"],
    "flag_bi": ["fr", "en"],
    "flag_bj": ["fr"],
    "flag_bl": ["fr"],
    "flag_bm": ["en"],
    "flag_bn": ["ms"],
    "flag_bo": ["es", "qu", "ay"],
    "flag_bq": ["en", "nl"],
    "flag_br": ["pt"],
    "flag_bs": ["en", "ht"],
    "flag_bt": ["ne"],
    "flag_bv": ["no"],
    "flag_bw": ["en"],
    "flag_by": ["be", "ru"],
    "flag_bz": ["en"],
    "flag_ca": ["en", "fr"],
    "flag_cc": ["ms"],
    "flag_cd": ["fr", "ln", "sw"],
    "flag_cf": ["fr"],
    "flag_cg": ["fr", "ln", "sw"],
    "flag_ch": ["de", "it", "fr"],
    "flag_ci": ["fr"],
    "flag_ck": ["mi"],
    "flag_cl": ["es", "ay"],
    "flag_cm": ["fr", "en"],
    "flag_cn": ["zh-CN", "zh-TW"],
    "flag_co": ["es"],
    "flag_cp": ["fr"],
    "flag_cr": ["es"],
    "flag_cu": ["es"],
    "flag_cv": ["pt"],
    "flag_cw": ["nl", "en", "es"],
    "flag_cx": ["en"],
    "flag_cy": ["el", "tr"],
    "flag_cz": ["cs"],
    "flag_de": ["de"],
    "flag_dg": ["en"],
    "flag_dj": ["so", "fr", "ar"],
    "flag_dk": ["da"],
    "flag_dm": ["en", "fr"],
    "flag_do": ["es"],
    "flag_dz": ["ar"],
    "flag_ea": ["es"],
    "flag_ec": ["es"],
    "flag_ee": ["et"],
    "flag_eg": ["ar"],
    "flag_eh": ["ar"],
    "flag_er": ["ti", "ar", "en"],
    "flag_es": ["es", "ca", "gl", "eu"],
    "flag_et": ["om", "am", "so", "ti"],
    "flag_fi": ["fi", "sv"],
    "flag_fj": ["en", "hi"],
    "flag_fk": ["en"],
    "flag_fm": ["en"],
    "flag_fr": ["fr"],
    "flag_ga": ["fr"],
    "flag_gb": ["en"],
    "flag_gd": ["en"],
    "flag_ge": ["ka"],
    "flag_gf": ["fr"],
    "flag_gg": ["en", "fr"],
    "flag_gh": ["en", "ak", "ee"],
    "flag_gi": ["en"],
    "flag_gl": ["da"],
    "flag_gm": ["en"],
    "flag_gn": ["fr"],
    "flag_gp": ["fr"],
    "flag_gq": ["es", "pt", "fr"],
    "flag_gr": ["el"],
    "flag_gs": ["ka", "ru", "az", "en"],
    "flag_gt": ["es"],
    "flag_gu": ["en"],
    "flag_gw": ["pt"],
    "flag_gy": ["en", "hi"],
    "flag_hk": ["yue", "zh"],
    "flag_hm": ["en"],
    "flag_hn": ["es"],
    "flag_hr": ["hr"],
    "flag_ht": ["ht"],
    "flag_hu": ["hu"],
    "flag_ic": ["es"],
    "flag_id": ["id"],
    "flag_ie": ["ga", "en"],
    "flag_il": ["he"],
    "flag_im": ["en"],
    "flag_in": ["hi"],
    "flag_io": ["en"],
    "flag_iq": ["ar", "ku"],
    "flag_ir": ["fa", "ku"],
    "flag_is": ["is"],
    "flag_it": ["it"],
    "flag_je": ["en", "fr"],
    "flag_jm": ["en"],
    "flag_jo": ["ar"],
    "flag_jp": ["ja"],
    "flag_ke": ["sw"],
    "flag_kg": ["ky"],
    "flag_kh": ["km"],
    "flag_km": ["ar"],
    "flag_kn": ["en"],
    "flag_kp": ["ko"],
    "flag_kr": ["ko"],
    "flag_kw": ["ar"],
    "flag_ky": ["en"],
    "flag_kz": ["kk"],
    "flag_la": ["lo"],
    "flag_lb": ["ar"],
    "flag_lc": ["en"],
    "flag_li": ["de"],
    "flag_lk": ["si", "ta"],
    "flag_lr": ["en"],
    "flag_ls": ["st"],
    "flag_lt": ["lt"],
    "flag_lu": ["lb"],
    "flag_lv": ["lv"],
    "flag_ly": ["ar"],
    "flag_ma": ["ar"],
    "flag_mc": ["fr"],
    "flag_md": ["ro"],
    "flag_me": ["sr", "bs"],
    "flag_mf": ["fr"],
    "flag_mg": ["mg"],
    "flag_mk": ["mk"],
    "flag_ml": ["fr"],
    "flag_mm": ["my"],
    "flag_mn": ["mn"],
    "flag_mo": ["zh-CN", "zh-TW"],
    "flag_mq": ["fr"],
    "flag_mr": ["ar"],
    "flag_ms": ["en"],
    "flag_mt": ["mt"],
    "flag_mu": ["en", "fr"],
    "flag_mv": ["dv"],
    "flag_mw": ["en"],
    "flag_mx": ["es"],
    "flag_my": ["ms"],
    "flag_mz": ["pt"],
    "flag_na": ["af"],
    "flag_nc": ["fr"],
    "flag_ne": ["fr", "ar"],
    "flag_ng": ["ha", "yo"],
    "flag_ni": ["es"],
    "flag_nl": ["nl"],
    "flag_no": ["no"],
    "flag_np": ["ne"],
    "flag_nz": ["mi"],
    "flag_om": ["ar"],
    "flag_pa": ["es"],
    "flag_pe": ["qu", "es"],
    "flag_pf": ["fr"],
    "flag_ph": ["en", "tl"],
    "flag_pk": ["ur"],
    "flag_pl": ["pl"],
    "flag_pm": ["fr"],
    "flag_pr": ["es"],
    "flag_ps": ["ar", "he"],
    "flag_pt": ["pt"],
    "flag_py": ["gn"],
    "flag_qa": ["ar"],
    "flag_re": ["fr"],
    "flag_ro": ["ro"],
    "flag_rs": ["sr"],
    "flag_ru": ["ru"],
    "flag_rw": ["rw"],
    "flag_sa": ["ar"],
    "flag_sb": ["en"],
    "flag_sc": ["fr", "en"],
    "flag_sd": ["ar"],
    "flag_se": ["sv"],
    "flag_sg": ["ms", "ta", "zh"],
    "flag_sh": ["en"],
    "flag_si": ["sl"],
    "flag_sj": ["no"],
    "flag_sk": ["sk"],
    "flag_sl": ["kri"],
    "flag_sm": ["it"],
    "flag_sn": ["fr"],
    "flag_so": ["so"],
    "flag_sr": ["nl"],
    "flag_ss": ["en"],
    "flag_st": ["pt"],
    "flag_sv": ["es"],
    "flag_sx": ["nl"],
    "flag_sy": ["ar"],
    "flag_sz": ["zu", "ts"],
    "flag_ta": ["en"],
    "flag_tc": ["en"],
    "flag_td": ["fr", "ar"],
    "flag_tf": ["fr"],
    "flag_tg": ["fr"],
    "flag_th": ["th"],
    "flag_tj": ["tg"],
    "flag_tl": ["pt"],
    "flag_tm": ["tk"],
    "flag_tn": ["ar"],
    "flag_tr": ["tr"],
    "flag_tt": ["en"],
    "flag_tw": ["zh-CN", "zh-TW"],
    "flag_tz": ["sw", "ar"],
    "flag_ua": ["uk"],
    "flag_ug": ["sw"],
    "flag_um": ["en"],
    "flag_us": ["en"],
    "flag_uy": ["en"],
    "flag_uz": ["uz"],
    "flag_va": ["it", "la"],
    "flag_vc": ["en"],
    "flag_ve": ["es"],
    "flag_vg": ["en"],
    "flag_vi": ["en"],
    "flag_vn": ["vi"],
    "flag_vu": ["fr", "en"],
    "flag_wf": ["fr"],
    "flag_ws": ["sm"],
    "flag_xk": ["sq", "sr"],
    "flag_ye": ["ar"],
    "flag_yt": ["fr"],
    "flag_za": ["zu", "xh", "af"],
    "flag_zm": ["ny"],
    "flag_zw": ["sn", "st", "xh"],
}
